version: '3.8'
services:
  
  frontend-google-test:
    build: .
    container_name: frontend-google-test
    restart: always
    ports:
      - 5173:5173
    volumes:
      - ./:/app
      - /app/node_modules
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host"]